config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
	validates :chefname, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
   format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensative: false }

   has_many :recipes

   has_secure_password
   validates :password, presence: true, length: { minimum: 5 }, on: :create

end

app/models/recipe.rb
class Recipe < ApplicationRecord
 validates :name, presence: true
 validates :description, presence: true, length: { minimum: 5, maximum: 500 }
 validates :chef_id, presence: true

 belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

def index
  @chefs = Chef.all
end




def new
	@chef = Chef.new
end

def create
  @chef= Chef.new(chef_params)
  if @chef.save
   flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
   redirect_to chef_path(@chef) 
  else
   render 'new' , status: 308
  end
end

def edit
  @chef = Chef.find(params[:id])
end


def update
  @chef = Chef.find(params[:id])
  if @chef.update(chef_params)
   flash[:success] = "Chef account was updated successfully!"
   redirect_to chef_path(@chef) 
  else
   render 'edit' , status: 308
  end
end

def show
 @chef = Chef.find(params[:id])
end


private

 def chef_params
  params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :set_recipe, only: [:show, :edit, :update]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.first
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe) 

    else
      render 'new' , status: 308
    end
  end


  def edit
  end


  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe) 

    else
      render 'edit' , status: 308
    end
  end


  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe was deleted successfully!"
    redirect_to recipes_path

  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper

 def gravatar_for(user, options = {size: 80})
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.chefname, class: "rounded-circle")
 end


end

app/views/chefs/_form.html.erb
<% show_password_fields = true if show_password_fields.nil? %>

<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-group row", role: "form"}) do |f| %>
      <div class="form-group row mb-3">
        <div class="col-form-label col-md-2 text-end">
          <%= f.label :chefname, "Choose Chefname" %>
        </div>

        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name" , autofocus: true %>
        </div>
      </div>

      <div class="form-group row mb-3">
        <div class="col-form-label col-md-2 text-end">
          <%= f.label :email %>
        </div>

        <div class="col-md-8">
          <%= f.email_field :email ,  class: "form-control", placeholder: "Enter your email" , autofocus: true %>
        </div>
      </div>

      <% if show_password_fields %>
        <div class="form-group row mb-3">
          <div class="col-form-label col-md-2 text-end">
            <%= f.label :password %>
          </div>

          <div class="col-md-8">
           <%= f.password_field :password ,  class: "form-control", placeholder: "Choose a password" , autofocus: true %>
          </div>
        </div>


        <div class="form-group row mb-3">
          <div class="col-form-label col-md-2 text-end">
            <%= f.label :password_confirmation, "Confirm password" %>
          </div>

          <div class="col-md-8">
            <%= f.password_field :password_confirmation ,  class: "form-control", placeholder: "Confirm password" , autofocus: true %>
          </div>
        </div>
      <% end %>

      <div class="form-group row mb-3">
        <div class=" offset-md-2 col-md-10">
          <%= f.submit(@chef.new_record? ? "Create my account" : "Update my account", class:"btn btn-primary btn-lg")%>
        </div>
      </div>
    <% end %>

   <div class="offset-md-5 col-md-4">
    [ <%= link_to "Cancel request and return to reciped listing", recipes_path %> ] 
   </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form', show_password_fields: false %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "Showing all chefs" %>
<div class="container">

<div class="row">


<div align="center">
  
 <% @chefs.each do |chef| %>
  <ul class="no-bullets">
    <div class="p-5 mb-2 bg-light grey text-black">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <li><%= link_to gravatar_for(chef), chef_path(chef)%></li>
        <li><%= link_to chef.chefname.capitalize, chef_path(chef) %></li>
        <li><small><%= pluralize(chef.recipes.count, "recpie") if chef.recipes %> </small></li>
      </div> 
    </div>
  </hr>
  </ul>
 <%end%>
</div>
</div>
</div>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Signup for the application" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile" %>

<div class="row">
	<div class="col-md-4 offset-md-4 center">
		<%= gravatar_for @chef, size: 180  %>
	</div>
</div>

<h4 align="center"> <%= @chef.chefname %>'s </h4>
<%= render 'recipes/recipe', obj: @chef.recipes %>

app/views/layouts/_footer.html.erb
<div class="b-example-divider"></div>

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2023 Company, Inc</p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-8 offset-md-2">
		<% flash.each do |name, msg| %>
		<div class="alert alert-<%=name%> alert-dismissible role="alert">
			<%=msg%>
			<a href="#" class="close text-right" data-bs-dismiss="alert" aria-label="Close">&times;</a>
		</div>
		<%end%>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <%= link_to "MyRecipies" ,root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Chefs", chefs_path%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Recipes
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-item"><%= link_to "Create a new recipe", new_recipe_path %></li>
             <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container-fluid"> <%= yield %> 
    </div>
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1 class="display-4">Welcome to my recipie</h1>
  <h2 class="lead">The best recpie sharing app</h2>
  <hr>
   <p><%= link_to "Signup today!", signup_path , class: "btn btn-danger btn-lg btn-xlarge"%></p>
</div>

<div class="row">
<div class="col-lg-4">
  <h2>Safari bug warning!</h2>
  <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
<div class="col-lg-4">
  <h2>Heading</h2>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
<div class="col-lg-4">
  <h2>Heading</h2>
  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
  <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
</div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
	<div class="col-md-12">

   <%= form_for(@recipe, :html => {class: "form-group row", role: "form"}) do |f| %>
    <div class="form-group row mb-3">
	    <div class="col-form-label col-md-2 text-end">
		  <%= f.label :name %>
	   </div>

	   <div class="col-md-8">
		  <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe" , autofocus: true %>
 	   </div>
   </div>

   <div class="form-group row mb-3">
      <div class="col-form-label col-md-2 text-end">
      <%= f.label :description %>
     </div>

     <div class="col-md-8">
      <%= f.text_area :description, rows: 10 ,  class: "form-control", placeholder: "Enter steps to create recipe" , autofocus: true %>
     </div>
   </div>

   <div class="form-group row mb-3">
    <div class=" offset-md-2 col-md-10">
      <%= f.submit class:"btn btn-primary btn-lg"%>
    </div>
   </div>
   <% end %>

   <div class="offset-md-5 col-md-4">

    [ <%= link_to "Cancel request and return to reciped listing", recipes_path %> ] 


   </div>
    



 </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
<div class="container">
<div class="row">
<div class="col-md-2">
 <section class="chef_info center">
   <%= gravatar_for(recipe.chef, size: 120) %>
   
 </section>
</div>

<div class="col-md-8"> 
  
  <div class="p-3 mb-2 bg-light grey text-black">
 <h4> <%= link_to recipe.name , recipe_path(recipe) %> </h4>
 <p> <%= truncate(recipe.description, length: 150) %> </p>
  <p>
   <span class="quiet"> <small> Created <%= time_ago_in_words(recipe.created_at) %> ago </small></span>
</p>
</div>
 
</div>
</div>
</div>

<%end%>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<% if @recipe.errors.any? %>

<div class="row mb-3">
  <div class="col-md-6 offset-md-3">
    <div class="card">
        <div class="card-header">
          <h2 class="card-title">
            <%= pluralize(@recipe.errors.count,"error") %>
            prohibted this <%= @recipe.class %> from being saved:
          </h2>
          <div class="card-body">
            <ul>
            <% @recipe.errors.full_messages.each do |msg| %>
             <li> <%= msg %> </li>
             <%end%>
             </ul>
           </div>
         </div>
       </div>
     </div>
   </div>
<%end%>


<div class="row">
	<div class="col-md-12">

   <%= form_for(@recipe, :html => {class: "form-group row", role: "form"}) do |f| %>
    <div class="form-group row mb-3">
	    <div class="col-form-label col-md-2 text-end">
		  <%= f.label :name %>
	   </div>

	   <div class="col-md-8">
		  <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe" , autofocus: true %>
 	   </div>
   </div>

   <div class="form-group row mb-3">
      <div class="col-form-label col-md-2 text-end">
      <%= f.label :description %>
     </div>

     <div class="col-md-8">
      <%= f.text_area :description, rows: 10 ,  class: "form-control", placeholder: "Enter steps to create recipe" , autofocus: true %>
     </div>
   </div>

   <div class="form-group row mb-3">
    <div class=" offset-md-2 col-md-10">
      <%= f.submit class:"btn btn-primary btn-lg"%>
    </div>
   </div>
   <% end %>

   <div class="offset-md-5 col-md-4">

    [ <%= link_to "Cancel request and return to reciped listing", recipes_path %> ] 


   </div>
    



 </div>
</div>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>
<div align="text-center col-md-8 off-set-md-4">
  <%= will_paginate%>
</div>

<%= render 'recipe', obj: @recipes %>

<div align="text-center">
  <%= will_paginate%>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>


<div class="container">
<div class="row">
<div class="col-md-8 offset-md-2"> 
  <div class="p-4 mb-3 bg-secondary text-black">
 <h4 class="center description"><strong>Steps: </strong> </h4>
 <hr/>
 <%= simple_format(@recipe.description) %>
 <hr/>

 <div class="float-right">

  <p class="d-flex justify-content-end center">
    <em>Created by:</em>
  </p>
  <p class="d-flex justify-content-end">
    <%= link_to gravatar_for(@recipe.chef),recipes_path %>
  </p>

  <p class="d-flex justify-content-end">
     <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="d-flex justify-content-end">Created: <%= time_ago_in_words(@recipe.created_at) %>  ago</div>
  </p>

 </div>
<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning"%>
  <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe"} ,
  class: "btn btn-xs btn-danger"%>
  <%= link_to "Return to recipe listing", recipes_path, class: "btn btn-xs btn-primary"%>
  



</div>
 </div>

</div>


</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row mb-3">
  <div class="col-md-6 offset-md-3">
    <div class="card">
        <div class="card-header">
          <h2 class="card-title">
            <%= pluralize(obj.errors.count,"error") %>
            prohibted this <%= obj.class %> from being saved:
          </h2>
          <div class="card-body">
            <ul>
            <% obj.errors.full_messages.each do |msg| %>
             <li> <%= msg %> </li>
             <%end%>
             </ul>
           </div>
         </div>
       </div>
     </div>
   </div>
<%end%>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr/>